units:
  # Proxy Spacing variables
  kx: cx
  ky: cy
  #Padding variables
  px: kx + 6
  py: ky + 6
  #positioning deets
  angle: 35       # Angle between halves
  pinky_stagger: 3
  pinky_splay: 5  # Degrees of splay between pinky and ring columns
  pinky_adj: -3   # Adjustment to compensate for splay spacing
  ring_splay: 3
  ring_adj: -8
  sf: 21.5  #switch footprint(square)
  # mcu constants
  nice_nano_x: 33.5
  nice_nano_y: 18
  mounting_hole_r: 1
points:
  zones:
    matrix:
        anchor.shift: [100, -100]
        rotate: -angle + pinky_splay + ring_splay
        mirror: &mirror
          ref: matrix_inner_top
          shift: [0.5sf, 0.5sf]
          distance: 40
        columns:
          pinky:
            #rows.top.skip: true
            rows.extra.skip: true
            key.column_net: P5
            key.mirror.column_net: P18
          ring:
            key.stagger: pinky_stagger
            key.splay: -pinky_splay
            key.origin: [0,pinky_adj]
            key.spread: 1.1kx
            #rows.extra.skip: true
            key.column_net: P6
            key.mirror.column_net: P15
          middle:
            key.stagger: 0.25ky
            key.splay: -ring_splay
            key.origin: [0, ring_adj]
            #rows.extra.skip: true
            key.column_net: P7
            key.mirror.column_net: P14
          index:
            key.stagger: -0.25ky
            key.column_net: P8
            key.mirror.column_net: P16
          inner:
            key.stagger: -0.5ky
            #rows.bottom.skip: true
            key.column_net: P9
            key.mirror.column_net: P10
        rows:
          bottom:
            row_net: P3
          home:
            row_net: P2
          top:
            row_net: P0
          extra:
            row_net: P1
  zones.thumb:
    anchor:
      ref: matrix_inner_bottom
      shift: [0, -20]
    mirror: *mirror
    columns:
      tucky:
        key.name: thumb_tucky
        key.shift: [-1.05ky,0]
        key.row_net: P4
        key.column_net: P8
        key.mirror.column_net: P16
        #key.mirror:
      reachy:
        key.stagger: 0
        ##key.splay: -5
        key.origin: [-kx/2, -kx/2]
        key.name: thumb_reachy
        key.row_net: P4
        key.column_net: P9
        key.mirror.column_net: P10
        #key.mirror:
zones.mcu:
  anchor:
    aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
    shift: [0, -0.7ky - 0.5nice_nano_y]
  key:
    name: mcu
    width: nice_nano_x
    height: nice_nano_y

zones.mounting_hole:
  anchor:
   ref: matrix_inner_home
   shift: [-0.5kx + 4, -ky + 4]
  mirror: *mirror
  key:
    name: mounting_hole
    width: 1
    height: 1

outlines:
    raw:
      - what: rectangle
        where: true
        size: [px,py]
    keys:
      - what: rectangle
        where: true
        size: [13.998, 14]
    board:
      - what: polygon
        operation: stack
        points:
          - ref: matrix_pinky_top
            shift: [-0.5px,0.5py]
          - ref: matrix_ring_top
            shift: [-0.75px,0.5py]
          - ref: matrix_ring_extra
            shift: [-0.5px,0.5py]
          - ref: matrix_index_extra
            shift: [-0.5px,0.75py]
          - ref.aggregate.parts: [matrix_inner_extra,mirror_matrix_inner_extra]
            shift: [0,15]
          - ref: mirror_matrix_index_extra
            shift: [-0.5px,0.75py]
          - ref: mirror_matrix_ring_extra
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_ring_top
            shift: [-0.75px, 0.5py]
          - ref: mirror_matrix_pinky_top
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_pinky_bottom
            shift: [-0.5px,-0.5py]
          - ref: mirror_matrix_middle_bottom
            shift: [-0.15px, -0.75px]
          - ref: mirror_thumb_tucky
            shift: [-0.5px,-0.5py]
          - ref: mirror_thumb_reachy
            shift: [0.65px,-0.65py]
          - ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
            shift: [10,-10.5]
          - ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
            shift: [-10,-10.5]
          - ref: thumb_reachy
            shift: [0.65px,-0.65py]
          - ref: thumb_tucky
            shift: [-0.5px,-0.5py]
          - ref: matrix_middle_bottom
            shift: [-0.15px, -0.75px]
          - ref: matrix_pinky_bottom
            shift: [-0.5px,-0.5py]
        fillet: 10
    combo:
          - name: board
          - operation: subtract
            name: keys
    switch_plate:
      - what: polygon
        operation: stack
        points:
          - ref: matrix_pinky_home
            shift: [-0.5px,0.5py]
          - ref: matrix_ring_top
            shift: [-0.5px,0.5py]
          - ref: matrix_index_extra
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_index_extra
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_ring_top
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_pinky_home
            shift: [-0.5px,0.5py]
          - ref: mirror_matrix_pinky_bottom
            shift: [-0.5px,-0.5py]
          - ref: mirror_thumb_tucky
            shift: [-0.5px,-0.5py]
          - ref: mirror_thumb_reachy
            shift: [0.5px,-0.5py]
          - ref: thumb_reachy
            shift: [0.5px,-0.5py]
          - ref: thumb_tucky
            shift: [-0.5px,-0.5py]
          - ref: matrix_pinky_bottom
            shift: [-0.5px,-0.5py]
        fillet: 20
    switch_plate_combo:
          - name: board
          - operation: subtract
            name: keys
pcbs:
  kel_to_pay:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu_nicenano:
        what: promicro
        params:
          orientation: "front"
        where:
          ref.aggregate.parts: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, 0]
          rotate: -90
      #mounting holes
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.4px, 0.55py]
      holeTopInner:
        what: mountinghole
        where:
          ref: [matrix_inner_extra]
          shift: [0,0.65py]
      holeBottomMiddle:
        what: mountinghole
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-0.65py]
      holeThumbReachy:
        what: mountinghole
        where:
          ref: [thumb_reachy]
          shift: [0, 0.65py]
      holeLeftMCU:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.65px,0.45py]
      holeRightMCU:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [0.65px,0.45py]
      holeMirrorThumbReachy:
        what: mountinghole
        where:
          ref: [mirror_thumb_reachy]
          shift: [0, 0.65py]
      holeMirrorBottomMiddle:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_bottom]
          shift: [0,-0.65py]
      holeMirrorTopInner:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_extra]
          shift: [0,0.65py]
      holeMirrorTopLeft:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinky_top]
          shift: [0.4px, 0.55py]
      #reset:
      #  what: button
      #  params:
      #    from: GND
      #    to: RST
      #  where:
      #    ref.aggregate.parts: [matrix_inner_home, mirror_matrix_inner_home]
      #    shift: [0, -2]
      #    rotate: 180
  switch_plate:
    outlines:
      main:
        outline: switch_plate_combo
    footprints:
      holeTopLeft:
        what: mountinghole
        where:
          ref: [matrix_pinky_top]
          shift: [0.4px, 0.55py]
      holeTopInner:
        what: mountinghole
        where:
          ref: [matrix_inner_extra]
          shift: [0,0.65py]
      holeBottomMiddle:
        what: mountinghole
        where:
          ref: [matrix_middle_bottom]
          shift: [0,-0.65py]
      holeThumbReachy:
        what: mountinghole
        where:
          ref: [thumb_reachy]
          shift: [0, 0.65py]
      holeLeftMCU:
        what: mountinghole
        where:
          ref: [matrix_inner_top]
          shift: [0.65px,0.45py]
      holeRightMCU:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_top]
          shift: [0.65px,0.45py]
      holeMirrorThumbReachy:
        what: mountinghole
        where:
          ref: [mirror_thumb_reachy]
          shift: [0, 0.65py]
      holeMirrorBottomMiddle:
        what: mountinghole
        where:
          ref: [mirror_matrix_middle_bottom]
          shift: [0,-0.65py]
      holeMirrorTopInner:
        what: mountinghole
        where:
          ref: [mirror_matrix_inner_extra]
          shift: [0,0.65py]
      holeMirrorTopLeft:
        what: mountinghole
        where:
          ref: [mirror_matrix_pinky_top]
          shift: [0.4px, 0.55py]
